### PR TITLE
feature(admin): admin users reset password endpoint in admin gateway

### PR DESCRIPTION
**Pull request by afkzoro**
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
This PR creates the reset password feature for admin users in `admin-gateway`.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

**Comment by Ahmard** [comment]
@afkzoro this endpoint is behaving more like "change password"
If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.

**Comment by afkzoro** [comment]
> @afkzoro this endpoint is behaving more like "change password"
> If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.

Oh okay then. @siradji suggested I keep out the complexities for now. But I don’t mind improving. I’ll send in a fix

**Comment by siradji** [comment]
> @afkzoro this endpoint is behaving more like "change password"
> 
> If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.

@Ahmard , is there any significance  for comparing the passwords that i missed? Super Admin creates an admin account with a default password. The route purpose is mainly to allow admin to reset the default password for privacy reason

**Comment by siradji** [comment]
> > @afkzoro this endpoint is behaving more like "change password"
> 
> > If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.
> 
> 
> 
> Oh okay then. @siradji suggested I keep out the complexities for now. But I don’t mind improving. I’ll send in a fix 

@afkzoro hold on the the fix. Till it is decided

**Comment by Ahmard** [comment]
> > @afkzoro this endpoint is behaving more like "change password"
> > If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.
> 
> @Ahmard , is there any significance for comparing the passwords that i missed? Super Admin creates an admin account with a default password. The route purpose is mainly to allow admin to reset the default password for privacy reason

Comparing old passwords is common nowadays, you can't be certain the person changing password is the actual owner of the account without it.
The current impl is for changing your own password, not for others(admin).

**Comment by siradji** [comment]
> > > @afkzoro this endpoint is behaving more like "change password"
> > > If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.
> > 
> > 
> > @Ahmard , is there any significance for comparing the passwords that i missed? Super Admin creates an admin account with a default password. The route purpose is mainly to allow admin to reset the default password for privacy reason
> 
> Comparing old passwords is common nowadays, you can't be certain the person changing password is the actual owner of the account without it. The current impl is for changing your own password, not for others(admin).

@Ahmard , this is been changed in the services and all authentication are handled in the gateways. An admin can only request to change their password when they are logged into the account. This is not a forget password feature. (won't be implementing that for security reason)

**Comment by Ahmard** [comment]
> > > > @afkzoro this endpoint is behaving more like "change password"
> > > > If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.
> > > 
> > > 
> > > @Ahmard , is there any significance for comparing the passwords that i missed? Super Admin creates an admin account with a default password. The route purpose is mainly to allow admin to reset the default password for privacy reason
> > 
> > 
> > Comparing old passwords is common nowadays, you can't be certain the person changing password is the actual owner of the account without it. The current impl is for changing your own password, not for others(admin).
> 
> @Ahmard , this is been changed in the services and all authentication are handled in the gateways. An admin can only request to change their password when they are logged into the account. This is not a forget password feature. (won't be implementing that for security reason)

Oh okay.
@afkzoro everything looks good to me.

**Review by siradji — APPROVED** [review]
LGTM

**Comment by siradji** [comment]
> > > > > @afkzoro this endpoint is behaving more like "change password"
> > > > > If that's what you're implementing, you should collect old password and compare it with the one stored in our DB.
> > > > 
> > > > 
> > > > @Ahmard , is there any significance for comparing the passwords that i missed? Super Admin creates an admin account with a default password. The route purpose is mainly to allow admin to reset the default password for privacy reason
> > > 
> > > 
> > > Comparing old passwords is common nowadays, you can't be certain the person changing password is the actual owner of the account without it. The current impl is for changing your own password, not for others(admin).
> > 
> > 
> > @Ahmard , this is been changed in the services and all authentication are handled in the gateways. An admin can only request to change their password when they are logged into the account. This is not a forget password feature. (won't be implementing that for security reason)
> 
> Oh okay. @afkzoro everything looks good to me.

Thanks @Ahmard

**Pull request merged**
